# numpy

In [1]:
import numpy as np

test = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

array([ 7, 12])

array([ 7, 12, 10, 15])

array([[ 7, 12],
       [10, 15]])

In [ ]:
np.diag(test[1:3,2:])

In [ ]:
np.concatenate((np.diag(test[1:3,2:]),np.diag(test[2:,1:4])),axis = 0)

In [ ]:
np.vstack((np.diag(test[1:3,2:]),np.diag(test[2:,1:4])))

In [ ]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])
np.concatenate((a, b), axis=0)

In [ ]:
np.diag(test[2:,2:])

In [ ]:
np.diag(test[1:3,2:])

In [ ]:
test = np.array([1,2,3,4])
test2 = np.array([[0],[1],[2],[3]])

test3 = test+ test2
test3

In [ ]:
test_1 = np.arange(1,13).reshape(4,3)
test_1

In [ ]:
test_2 = np.arange(10,40,10)
test_2