In [2]:
def func(a ,b= []):
	b.append(a)
	print(b)
# 	return b

In [3]:
func(3,)
func(4,)

[3]
[3, 4]


In [4]:
t = func(10)

[3, 4, 10]


# _사용하기

In [ ]:
# a, _, b = 1, 3, 2 # 특정 값을 skip하고 싶을 때 _ 사용
# '''
# a = 1 ,   ,b = 2
# '''


def add(x):
    a = x + 1
    b = x - 1
    return a ,b

for i in range(5):
    a = add(i) # add(x)에서 return 되는 값 중에서 하나만 받기 원하는 경우
    print(a)
'''

'''


In [ ]:
# 과제

In [1]:
import numpy as np

In [2]:
data_size = 100
input_dim = 3

In [3]:
input_data = np.random.normal(size=(data_size, input_dim))

In [4]:
output_data_binary = np.random.choice([0, 1], size=(data_size, 1))

In [34]:
#초기 가중치 값
def NN_weight(x_size,y_size):
    weight = np.random.rand(x_size,y_size)
#     weight = np.transpose(weight)
    return weight

#활성화 함수 sigmoid
def sigmoid(x):
    return 1/(1+np.exp(-x))

#sigmoid 미분
def g_sigmoid(x):
    result = sigmoid(x) 
    return result*(1-result)

#2번째 층 역전파
def gd(input_value,result,output_value):
    error = result - output_value
    error2 = g_sigmoid(result)
    total_error = error * error2 * input_value
    return total_error

#1번째 층 역전파
def gd2(weight,result,output_value):
    error = result - output_value
    error2 = g_sigmoid(result)
    error3 = sum(weight)
    total_error = error * error2 * error3    
    return total_error



In [40]:
np.random.seed(1818)
data_size = 100
input_dim = 3
learning_rate = 0.01
epochs = 5

#데이터 input, output
input_data = np.random.normal(size=(data_size, input_dim))
output_data_binary = np.random.choice([0, 1], size=(data_size, 1))
output_data_binary_copy = output_data_binary
# output_data = np.random.normal(0, 2, size=(data_size, 1))

# weight 값
weight_1 = NN_weight(4,3)
weight_2 = NN_weight(1,4)


# for i in range(epochs):    
#     for j in input_data:
        
input_data = input_data[0]
x_1 = np.dot(weight_1,input_data)       
x_1_result = sigmoid(x_1)

x_2 = np.dot(x_1_result,weight_2)        
x_2_result = sigmoid(x_2)

#역전파
#2번째 층
output_data_binary_copy_value = output_data_binary_copy[0]
total_error_1 = gd(x_1_result,x_2_result,output_data_binary_copy_value)
weight_2_2 = weight_2 -  learning_rate * total_error_1

#1번째 층
total_error_2 =gd2(weight_1,x_2_result,output_data_binary_copy_value)
weight_1_2 = weight_1 - learning_rate * total_error_2

# weight 업데이트
weight_2 = weight_2_2
weight_1 = weight_1_2









[[0.71256851 0.65096421 0.55515276]
 [0.97381289 0.56757349 0.89981307]
 [0.23873919 0.81243772 0.97260196]
 [0.82455345 0.22914407 0.38316227]]
[ 0.68557885 -1.64395482  2.2276003 ]


ValueError: shapes (4,) and (1,4) not aligned: 4 (dim 0) != 1 (dim 0)

In [33]:
a = [[1],[2],[3],[4]]
b = [[3],[4],[5],[6]]
c = b-a

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [17]:
input_data = np.random.normal(size=(data_size, input_dim))

weight_1 = NN_weight(4,3)
weight_2 = NN_weight(1,4)

# input_data = input_data[0]
x_1 = np.dot(input_data,weight_1)