In [ ]:
a = [1,2,3,4,5]
print(a[-2:1:-1])

In [ ]:
class Test:
    def __init__(self,a):
        self.__a = a
        _a = __a
        return _a
        
test = Test(3)
print(test._a)

# _사용하기

In [ ]:
# a, _, b = 1, 3, 2 # 특정 값을 skip하고 싶을 때 _ 사용
# '''
# a = 1 ,   ,b = 2
# '''


def add(x):
    a = x + 1
    b = x - 1
    return a ,b

for i in range(5):
    a = add(i) # add(x)에서 return 되는 값 중에서 하나만 받기 원하는 경우
    print(a)
'''

'''


In [ ]:
# 과제

In [2]:
import numpy as np

In [3]:
data_size = 100
input_dim = 3

In [ ]:
input_data = np.random.normal(size=(data_size, input_dim))

In [ ]:
output_data_binary = np.random.choice([0, 1], size=(data_size, 1))

In [22]:
#초기 가중치 값
def NN_weight(x_size,y_size):
    weight = np.random.rand(x_size,y_size)
    weight = np.transpose(weight)
    return weight

#활성화 함수 sigmoid
def sigmoid(x):
    return 1/(1+np.exp(-x))

#sigmoid 미분
def g_sigmoid(x):
    result = sigmoid(x) 
    return result*(1-result)

#2번째 층 역전파
def gd(input_value,result,output_value):
    error = result - output_value
    error2 = g_sigmoid(result)
    total_error = error * error2 * input_value
    return total_error

#1번째 층 역전파
def gd2(weight,result,output_value):
    error = result - output_value
    error2 = g_sigmoid(result)
    error3 = sum(weight)
    total_error = error * error2 * error3    
    return total_error



In [24]:
np.random.seed(1818)
data_size = 100
input_dim = 3
learning_rate = 0.01
epochs = 5

#데이터 input, output
input_data = np.random.normal(size=(data_size, input_dim))
output_data_binary = np.random.choice([0, 1], size=(data_size, 1))
output_data_binary_copy = output_data_binary
# output_data = np.random.normal(0, 2, size=(data_size, 1))

# weight 값
weight_1 = NN_weight(4,3)
weight_2 = NN_weight(1,4)

for i in range(epochs):    
    for j in input_data:
        print(j)
        input_data = j
        x_1 = np.dot(input_data,weight_1)       
        x_1_result = sigmoid(x_1_1)

        x_2 = np.dot(x_1_result,weight_2)        
        x_2_result = sigmoid(x_2_1)

        #역전파
        #2번째 층
        output_data_binary_copy_value = output_data_binary_copy[0]
        total_error_1 = gd(x_1_result,x_2_result,output_data_binary_copy_value)
        weight_2_2 = weight_2 -  learning_rate * total_error_1

        #1번째 층
        total_error_2 =gd2(weight_1,x_2_result,output_data_binary_copy_value)
        weight_1_2 = weight_1 - learning_rate * total_error_2

        # weight 업데이트
        weight_2 = weight_2_2
        weight_1 = weight_1_2








[ 0.68557885 -1.64395482  2.2276003 ]
[ 0.73985081 -1.58354479 -0.25188183]
[-1.89483289 -2.08861807  3.22106635]
[-0.33029932  0.1870469  -1.14582145]
[ 0.25207133 -1.0832996  -1.86554571]
[-0.61819653  1.22058326  0.55604944]
[-1.78966784 -0.31346542  1.93338345]
[-0.12023239  0.49169313 -1.71384589]
[ 0.98539074  0.93926651 -0.36008968]
[ 0.75039846 -0.50013797 -2.36297489]
[ 0.4419916   0.69232606 -1.23118382]
[-0.8694799   2.53419987 -0.08990004]
[ 0.01989394 -0.03087087  0.58662626]
[ 0.18713048  0.31126714 -0.13551842]
[-0.88927929 -0.20070831 -0.49886332]
[ 0.32773524 -0.12361617 -0.88266022]
[0.65999078 0.16560455 1.30865547]
[-0.72581646 -0.18258016 -1.97429767]
[-1.20824454 -0.10398977 -1.08660699]
[-0.45052348  0.5155556  -2.21341454]
[ 1.53135226  0.65562671 -0.81033476]
[0.00416025 1.0426386  2.00212739]
[ 0.10146944  0.63821031 -0.1250047 ]
[-0.17784667  1.41450038  0.07773544]
[ 0.86431989  0.81925478 -0.16424178]
[ 0.27865898  0.6570594  -1.87547809]
[ 0.74530613 -0.97

TypeError: 'numpy.float64' object is not iterable

In [17]:
input_data = np.random.normal(size=(data_size, input_dim))

weight_1 = NN_weight(4,3)
weight_2 = NN_weight(1,4)

# input_data = input_data[0]
x_1 = np.dot(input_data,weight_1)