In [2]:
import numpy as np
import numpy.linalg as lin

In [3]:

#2개인 경우 ,첫번째 행 [1,1], 두번째행 [2,1]
a=np.array([[1,1],[2,1]])
print(a)
print(a.shape)

#역행렬정의
a_=lin.inv(a)
print(a_)

[[1 1]
 [2 1]]
(2, 2)
[[-1.  1.]
 [ 2. -1.]]


In [3]:
#y는 1차원 벡터, 행렬이 아님
y=np.array([2,4])
print(y.shape)
#
y_1=np.array([[2,4]])
print(y_1)
print(y_1.shape)

(2,)
[[2 4]]
(1, 2)


In [4]:
#column vector
y_2=np.array([[2],[4]])
print(y_2)
print(y_2.shape)

print("-------------------------------")

#column vector
y_3=np.array([2,4]).reshape(2,1)
print(y_3)

[[2]
 [4]]
(2, 1)
-------------------------------
[[2]
 [4]]


In [5]:
#두개의 행렬 곱하기
w=np.matmul(a_,y)
print(w)

print("-------------------------------")

w_1=np.matmul(a_,y_3)
print(w_1)


[2. 0.]
-------------------------------
[[2.]
 [0.]]


In [6]:
#3개의 경우
a=np.array([[1,1],[2,1],[3,1]])
a_=lin.pinv(a)
print(a_)
print("-------------------------------")
y=np.array([2,4,6.4]).reshape(3,1)
w=np.matmul(a_,y)
print(w)

[[-5.00000000e-01 -3.19189120e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]
-------------------------------
[[ 2.2       ]
 [-0.26666667]]


In [8]:
x_=np.array([[-1,1],[0,1],[1,1],[2,1]])
np.matmul(x_,w)

array([[-2.46666667],
       [-0.26666667],
       [ 1.93333333],
       [ 4.13333333]])